/* PcapLens tests: runs the shared engine over the corpus and compares
   every field against tests/expected.json (generated by oracle.py using
   real scapy; IPv4 header checksums verified independently in python). */
'use strict';
const fs=require('fs'),path=require('path');
const engine=require(path.join(__dirname,'..','engine.js'));
function loadPcap(p){
  if(fs.existsSync(p))return new Uint8Array(fs.readFileSync(p));
  const b=p+'.b64';
  if(fs.existsSync(b))return new Uint8Array(Buffer.from(fs.readFileSync(b,'utf8').trim(),'base64'));
  throw new Error('missing corpus '+p);
}
const items=JSON.parse(fs.readFileSync(path.join(__dirname,'expected.json'),'utf8')).items;
let fail=0,pass=0;
function eq(a,b,label){
  if(a===b){pass++;return;}
  fail++;console.log('FAIL '+label+': got '+JSON.stringify(a)+' want '+JSON.stringify(b));
}
function approx(a,b,tol,label){
  if(typeof a==='number'&&Math.abs(a-b)<=tol){pass++;return;}
  fail++;console.log('FAIL '+label+': got '+a+' want ~'+b);
}
function layer(got,want,names,L){
  if(want===undefined){return;}
  if(!got){fail++;console.log('FAIL '+L+'layer missing');return;}
  for(const k of names)if(want[k]!==undefined)eq(got[k],want[k],L+k);
}
for(const item of items){
  const bytes=loadPcap(path.join(__dirname,'corpus',item.file));
  const r=engine.parsePcap(bytes);
  const T=item.file+' ';
  if(item.expect_warning){
    if(r.warnings.some(w=>w.indexOf(item.expect_warning)>=0)){pass++;}
    else {fail++;console.log('FAIL '+T+'missing warning containing '+item.expect_warning+' (got '+JSON.stringify(r.warnings)+')');}
    continue;
  }
  eq(r.errors.length,0,T+'errors '+JSON.stringify(r.errors));
  eq(r.nano,item.nano,T+'nano');
  eq(r.little_endian,item.little_endian,T+'little_endian');
  eq(JSON.stringify(r.version),JSON.stringify(item.version),T+'version');
  eq(r.snaplen,item.snaplen,T+'snaplen');
  eq(r.linktype,item.linktype,T+'linktype');
  eq(r.packets.length,item.count,T+'packet count');
  for(let i=0;i<item.packets.length;i++){
    const e=item.packets[i],p=r.packets[i],L=T+'pkt'+i+' ';
    if(!p){fail++;console.log('FAIL '+L+'missing');continue;}
    eq(p.ts_sec,e.ts_sec,L+'ts_sec');
    eq(p.ts_frac,e.ts_frac,L+'ts_frac');
    eq(p.incl_len,e.incl_len,L+'incl_len');
    eq(p.orig_len,e.orig_len,L+'orig_len');
    eq(p.offset,e.offset,L+'offset');
    approx(p.ts,e.ts,1e-9,L+'ts float');
    eq(p.payload_len,e.payload_len,L+'payload_len');
    if(e.ip_chksum_ok!==undefined)eq(p.ip&&p.ip.chksum_ok,e.ip_chksum_ok,L+'ip_chksum_ok');
    layer(p.eth,e.eth,['src','dst','type'],L+'eth.');
    layer(p.ip,e.ip,['src','dst','proto','ttl','len','id','flags','chksum','ihl_words','version'],L+'ip.');
    layer(p.ipv6,e.ipv6,['src','dst','nh','hlim','plen'],L+'ipv6.');
    layer(p.tcp,e.tcp,['sport','dport','seq','ack','flags','window','chksum'],L+'tcp.');
    layer(p.udp,e.udp,['sport','dport','len','chksum'],L+'udp.');
    layer(p.icmp,e.icmp,['type','code','id','seq'],L+'icmp.');
    layer(p.icmpv6,e.icmpv6,['kind','id','seq'],L+'icmpv6.');
    layer(p.arp,e.arp,['op','psrc','pdst','hwsrc','hwdst'],L+'arp.');
    layer(p.dns,e.dns,['id','qr','qdcount','ancount','qname','qtype','answer','ttl'],L+'dns.');
  }
}
console.log(pass+' passed, '+fail+' failed');
process.exit(fail?1:0);
